[bastion]
bastion_host ansible_host=93.77.185.229

[webservers]
web-a ansible_host=10.0.1.33
web-b ansible_host=10.0.2.8

[prometheus]
prometheus_server ansible_host=10.0.2.19

[grafana]
grafana_server ansible_host=10.0.2.38

[elasticsearch]
elasticsearch_server ansible_host=10.0.2.11

[kibana]
kibana_server ansible_host=10.0.2.20 external_ip=158.160.1.33

[all:vars]
ansible_user=student
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q student@93.77.185.229"'
